name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Deploy API
        run: ./deploy-server.sh

      - name: Deploy Client
        run: ./deploy-client.sh
